# =============================================================================
# Messager - Production overrides
# =============================================================================
#
# Start the production stack:
#   docker compose -f compose.yaml -f compose.prod.yaml up -d
#
# Rebuild after a code change:
#   docker compose -f compose.yaml -f compose.prod.yaml up -d --build
#
# The app is available at:
#   https://www.messager.org
#
# Caddy obtains TLS certificates automatically via Let's Encrypt (HTTP-01).
# Ports 80 and 443 are exposed on standard ports for ACME challenge compatibility.
# =============================================================================

services:

  mysql:
    volumes:
      - /mnt/data/mysql:/var/lib/mysql
    deploy:
      restart_policy:
        condition: any

  caddy:
    build:
      context: .
      dockerfile: docker/caddy/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - asset_data:/var/www/public/assets
    deploy:
      restart_policy:
        condition: any

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: base
    volumes:
      - asset_data:/var/www/public/assets
    deploy:
      restart_policy:
        condition: any

  worker1:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: worker
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: any

  worker2:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: worker
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: any

  worker3:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: worker
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: any

  cron:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: cron
    deploy:
      restart_policy:
        condition: any

volumes:
  caddy_data:
  caddy_config:
  asset_data: