# =============================================================================
# Messager - Production overrides
# =============================================================================

services:

  mysql:
    image: mysql:8.0
    volumes:
      - /mnt/data/mysql:/var/lib/mysql
    deploy:
      restart_policy:
        condition: any

  caddy:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - asset_data:/var/www/public/assets
    deploy:
      restart_policy:
        condition: any

  php:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-base:latest
    volumes:
      - asset_data:/var/www/public/assets
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

  worker1:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-worker:latest
    depends_on:
      - mysql
    volumes:
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

  worker2:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-worker:latest
    depends_on:
      - mysql
    volumes:
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

  worker3:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-worker:latest
    depends_on:
      - mysql
    volumes:
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

  worker4:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-worker:latest
    depends_on:
      - mysql
    volumes:
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

  cron:
    image: europe-west9-docker.pkg.dev/messager-486910/messager-repo/php-cron:latest
    volumes:
      - ./.env.prod.local:/var/www/.env.prod.local:ro
    deploy:
      restart_policy:
        condition: any

volumes:
  caddy_data:
  caddy_config:
  asset_data:
