# =============================================================================
# Messager - Development overrides (auto-loaded by `docker compose up`)
# =============================================================================
#
# Start the dev stack:
#   docker compose up -d
#
# The app is available at:
#   http://localhost:90
#
# MySQL is accessible from the host at:
#   mysql -h 127.0.0.1 -P 3316 -u root messager
#
# All host ports are offset by +10 to avoid collisions with other projects.
# =============================================================================

services:

  mysql:
    user: "1000:1000"
    ports:
      - "3316:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  caddy:
    build:
      context: ./docker/caddy
    ports:
      - "90:80"
    volumes:
      - .:/var/www
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/logs:/var/log/caddy
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
    user: "1000:1000"
    ports:
      - "9010:9000"
    volumes:
      - .:/var/www

  worker1:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: worker
    user: "1000:1000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    restart: unless-stopped

  worker2:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: worker
    user: "1000:1000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    restart: unless-stopped

  worker3:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: worker
    user: "1000:1000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    restart: unless-stopped
