FROM caddy:2

# Note: Context is project root
COPY docker/caddy/Caddyfile.prod /etc/caddy/Caddyfile
COPY public /var/www/public
COPY assets /var/www/assets
COPY vendor /var/www/vendor

WORKDIR /var/www

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
