<?php

namespace App\Entity\Twilio;

use App\Repository\Twilio\TwilioStatusRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TwilioStatusRepository::class)]
class TwilioStatus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null; // @phpstan-ignore property.unusedType (auto-generated by Doctrine)

    #[ORM\Column(length: 64)]
    private ?string $sid = null;

    #[ORM\Column(length: 64)]
    private ?string $status = null;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $receivedAt;

    public function __construct()
    {
        $this->receivedAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSid(): ?string
    {
        return $this->sid;
    }

    public function setSid(string $sid): static
    {
        $this->sid = $sid;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getReceivedAt(): \DateTime
    {
        return $this->receivedAt;
    }

    public function setReceivedAt(\DateTime $receivedAt): static
    {
        $this->receivedAt = $receivedAt;

        return $this;
    }
}
